spring:
  application:
    name: activity-service
  data:
    mongodb:
    url: mongodb://localhost:27017/fitness_activity
    database: fitness_activity

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

