spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db
    username: root
    password: Kushlu@123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
